### ISSUE TITLE
M5: Coding - Implement User Registration and User Profile

### ISSUE THREAD

**Issue by nancytao** [seantitus/WaterReporting#11]
### Details of Implementation 
- Add the registration screen to your app. A new user should be able to register by entering their information (like name, id, and password). If accepted, the new user should be added to the system. If cancelled, the user should not be added.
- During registration, the new user may designate their account type (User, Worker, Manager or Admin). In a real application, we would have controls for these, but for this class project, we will let the individual enter their capabilities during registration.
- You should also have the ability for a user to create and edit their profile. Their profile consists of all their information that the application must maintain like email address, home address, title, etc.

### To-Do List
- [x] Enum for User type (regular user, worker, manager, admin) 
- [x] New Registration Activity 
- [x] New Registration View with various fields including username, password, email address and cancel button 
- [x] User class updated with new fields including username, password, email address, home address, title, etc with getters and setters 
- [x] Model gets updated (UserUpdater class) 
- [x] User profile can be accessed, and updates the Model
- [x] Javadocs/comments 

### Done Done Criteria
- [x] User registration screen is integrated into app .............................. 05
- [x] Accepted registration adds new user to system ................. 05
- [x] Cancelled registration does not add new user ................. 05
- [x] Back-end records list of registered users (UI communicates with model) ................... 10
- [x] User type (user, worker, manager, admin) created ..... 10
- [x] User profile edited, has fields like username, password, email address, home address, title, etc ...... 05
- [x] Javadoc / comments .......................................... 05

**Comment by nancytao** [comment]
All sub-tasks completed, closing
