### ISSUE TITLE
M6: Implement submit a Water Report feature 

### ISSUE THREAD

**Issue by nancytao** [seantitus/WaterReporting#15]
Implement the ability to submit the user water reports. You should have some kind of input screen for the report where all the information is captured. The report should be stored somewhere in the model.

### To-Do List 
- [x] Create Water Report Model object, with an auto-incremented ID (see M3 student ID for inspiration) 
- [x] Create submit Activity 
- [x] Create submission view that allows all required information to be stored, with a cancel button 
- [x] Update Model, likely by creating a ReportUpdater helper class 
- [x] Create view for viewing list of reports 
- [x] Populate list view with Reports from Model 
- [x] Javadocs/Comments 

### Done Done Criteria 

- [x] Login/Registration/Profile still works ...... 05
- [x] Can navigate to Submit report functionality ...................... 05
- [x] Report screen enters all required information .................... 10
- [x] After submission report is stored in model ....................... 10
- [x] List of reports can viewed.................................10
- [x] Cancel does not save the report .......................... 05
- [x] Report number auto-assigned by system .................... 05
- [x] Javadoc, Comments and Design Update / discussion with TA ........................................10
