### ISSUE TITLE
M7: Water Availability Screen with map 

### ISSUE THREAD

**Issue by nancytao** [seantitus/WaterReporting#17]
### Information 
Implement the water availability screen. This screen should display a Map (you can use any api you wish, although google maps is pretty well documented.). The map should have markers at each location that water has been reported. Clicking on the pin should provide information from the water report.

### To-Do List (tentative) 

- [x] Use Google Maps API - see the example code on T^2
- [x] Display the map, create a new View 
- [x] Show markers on the map, only for where reports are located
- [x] Selecting a pin should choose the correct report from the Model 

### Done Done Criteria 
- [x] Previous functionality still works ................................. 05
- [x] Navigation option to show water availability screen .............. 05
- [x] Map displays ................. 15
- [x] Pins are on map at each report location .............. 10
- [x] Selecting a pin shows details of the report .......... 10
- [x] Javadocs and code style, Design Discussion ............... 15

**Comment by seantitus** [comment]
tested
